[package]
name = "cukurova-yemekhane"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-macros = "0.2.4"
chrono = "0.4"
reqwest = "0.12"
serde = "1.0"
serde_json = "1.0"
tokio = "1"